### LOGIN
POST http://localhost:8000/api/accounts/login
Content-Type: application/json

{
    "email": "zdb@msn.com",
    "password": "pouet"
}

### REGISTER
POST http://localhost:8000/api/accounts/register
Content-Type: application/json

{
    "email": "zdb@msn.com",
    "password": "pouet",
    "username": "oiazero"
}

### GET all users
GET http://localhost:8000/api/users


### GET one user
GET http://localhost:8000/api/users/19


