### LOGIN
POST http://localhost:8000/api/account/login
Content-Type: application/json

{
    "email": "yligotmi@msn.com",
    "password": "pouetpouet"
}

###
GET http://localhost:8000/api/users/1

###
GET http://localhost:8000/api/recipes
Cookie: 'access_token'=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlzcyI6ImJhdGNoLWNvb2tlciIsInNjb3BlcyI6WyJhZG1pbiIsInVzZXIiXSwiaWF0IjoxNjAxMDk5NjA3LCJleHAiOjE2MDExMDMyMDd9.jVrxX7FdK_GFfByqr4cWZTKpOi8_jCmOYuhxNYtFm1Q
Content-Type: application/json

{
    "ingredientName": "melfort",
    "quantity": 100,
    "category": "assaisonnements et condiments",
    "unity": "cl"
}

###
GET http://localhost:8000/api/tags

###
PUT http://localhost:8000/api/tags/1
Content-Type: application/json

{
    "tagname": "pouet"
}
###

POST http://localhost:8000/api/recipes
Content-Type: application/json

{
    "creatorId": 2,
    "name": "test retour id",
    "image": null,
    "url": null,
    "content": "Recette pour tester le retour id "
}
###

DELETE http://localhost:8000/api/recipes/8

###

GET http://localhost:8000/api/recipes/1/ingredients/13

###

POST http://localhost:8000/api/recipes/8/ingredients
Content-Type: application/json

{
    "name": "ketchup",
    "category": "assaisonnements et condiments",
    "quantity": 200,
    "unity": "cl"    
}
###

GET http://localhost:8000/api/recipes/8/ingredients/10

###

PUT http://localhost:8000/api/recipes/8/ingredients/10
Content-Type: application/json

{
    "quantity": 100,
    "unity": "cl"    
}

###

DELETE http://localhost:8000/api/recipes/8/ingredients/10

###